### ISSUE TITLE
We need to be able to tell which dependencies are corporate / internal dependencies

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#102]
As a part of this, we need to implement labels for dependencies that can store this generic information about a dependency that changes from provider to provider. For instance, a dependency could be `open-source`, `embedded`, `internal` etc.

**Comment by shawn-hurley** [comment]
I am going to propose that we: 

1. Have a new label field on the dependency, we will have specific labels for dependencies that mean something, for now lets call it `konveyor.io/dep-source` the expected values are `open-source`, `internal`.
2. Any provider, can set these labels or not, for the java provider, there will be a new provider specific config that will give it a list of dependencies that will be considered `open-source`. If it is not in that list then it is considered `internal`.
3. We add the ability, for the engine, given a flag, say `--skip-open-source` that can only be set and/or used when the provider/analysisMode is full, to look for any of the incidents that are coming from a dependency that are in the `open-source` list. 
4. We can then expand this by providing a list of include, exclude deps in a file, that can be passed to the analysis via CLI flags. 

for this to work we need to have a standard way of identifying dependencies across all providers so that we can compare, and it has to be findable based on the URI or a new field that the provider sets on a given incident. 

I think a new field would be the best approach, as it would give us the best integration to other languages and how they determine dependencies.

For java, it is simple as we already implemented similar logic with the new uri `konveyor-jdt` that the bundle is setting.

@fabianvf @pranavgaikwad Please give this a look over and let me know if you agree or disagree or if you see dragons?

**Comment by fabianvf** [comment]
I'm wondering if we could do this by just using labels on the discovered dependencies, and having everything else in the `providerSpecificConfig` for java. So I guess I'm following step 1, step 2 is fine since it's all provider-specific, step 3 I'm not totally following since I feel like that's lifting provider-specific configuration to the top level, and same with 4 (since you could have a path to an exclude file in the `providerSpecificConfig`)

**Comment by shawn-hurley** [comment]
hmm, do we have a filter-dips flag instead that just re-uses the labels selectors? I think that make sense. for 4 we add a providerSpecificConfig that takes file or list of deps, and then will label them with the value given.

I think this makes sense. does that make sense to you? @fabianvf

**Comment by fabianvf** [comment]
yeah, we could add a top-level flag, or we could have it be provider-specific config as well. We've talked about exposing provider-specific config via the CLI already, so we could put it in the config file for now and expand it to the CLI when we go that direction.
