### ISSUE TITLE
Consolidating Categories

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#88]
## Current State
Today there are 4 Categories in the windup project.

1. Potential
2. Mandatory
3. Information
4. optional

The potential is supposed to mean that the Rule ran successfully, and there may or may not be an issue. We can't tell.

Mandatory is that the Rule ran correctly and the Rule states this must be fixed

Information is that the Rule ran correctly, and the Rule states that this is just for information, which could mean there is a problem in the future but not something you must fix.

Optional is that a rule ran unsuccessfully, and it might have a violation and may not.

## Proposed State

Consolidating these and making it easier for both end users to understand what the category is supposed to mean and what a rule writer should set is the goal of this issue. 

For the Rule's categories, I am proposing two mutually exclusive buckets. 

1. **Mandatory** will be when the Rule states that this must be fixed based on the ruleset. This will only be set for rules that have run successfully
2. **Potential** will be when the Rule states this is potentially an issue. This will only be set for rules that have run successfully

We need to create a new bucket for partial matches/errors. I would prefer to call this something like Errors, which will be different than the violations that use the categories above. In this world, we would have two new error categories:

1. Partial Match -> This Rule ran semi-successfully, and some conditions matched, but there were failures in others. This should include the error message and other stuff 
2. Failure -> this Rule did not run successfully in any way.

We also need a third bucket of rules for rules that ran successfully but did not have any violations. I believe this should just be something like PassedRules or something.

We should discuss the names here so that once we implement it, we can point back to this. 

Adding in folks that this will probably have an impact on:
@rromannissen @jortel @ibolton336 @pranavgaikwad @fabianvf

**Comment by shawn-hurley** [comment]
Another thing to consider is that we want a whole new structure for things that have tagging.

**Comment by rromannissen** [comment]
I don't agree with this classification, which I think comes from a misunderstanding of what the categories in Windup actually mean. Let me explain further:

- **Mandatory** means that an issue that has been found has to be addressed for the application to work at all in the target environment or technology. For example, a certain API has breaking changes so updates in the code are required.
-  **Optional** is used for changes that would be desirable and are not strictly required when migrating to the target environment or technology. For example, addressing deprecated APIs or leveraging some capabilities that the target platforms offers.
- **Potential** makes sense for stuff that has been detected for which we don't have an explicit path forward. For example, when migrating from Weblogic to EAP, there are rules that address certain things that have been identified, but there are also other "catch all" rules that look for Oracle packaging. We are not certain about those packages being a problem, but they could potentially be due to its proprietary nature.
- **Information** provides extra information about things that were found during the analysis. Things like "there's a Maven POM file", "this application is using embedded Hibernate" or "I found some Spring configuration descriptors". I've always struggled to understand why these are issues, and I think they should be considered facts instead in the future, as they only provide metadata about the application and are not expected to be addressed.

As you can see, the categories don't have anything to do with the rule being executed successfully or not, although I agree with the value of knowing when a rule failed or has partial matches, which I think are not addressed in Windup, but that's probably something that is not strictly related to categories.

Nevertheless, I might be wrong with all of that, I'd be curious to hear @jmle 's thoughts on this.

**Comment by jmle** [comment]
I agree with @rromannissen, especially because I think that losing the "optional" category would mean losing value for the user. It is useful to know that something has been found that can be addressed now, but implies no risk in the migration process in case it's not.

It might be that the difference between "optional" and "potential" is not clear enough, maybe some name change could be done in that case ("inconclusive" instead of "potential"?), but the docs should supply specific definitions of these terms.

So I think it makes sense to have at least those three classifications: things that must be changed, things that may need to be changed, and things that you can change if you want but nothing happens for the moment if you don't.

**Comment by shawn-hurley** [comment]
> So I think it makes sense to have at least those three classifications: things that must be changed, things that may need to be changed, and things that you can change if you want but nothing happens for the moment if you don't.

Can someone help me understand what the difference is for the end user between the last two? In my mind, it feels like they are the same thing to the end user, something that a rule found, that the rule author has determined is not Mandatory and the user gets to choose what to do next. 

I think there is a distinction to be clear, just trying to understand what choice a user would make if they had that distinction.

**Comment by jmle** [comment]
@shawn-hurley `potential` usually implies that the analyzer doesn't have enough information to determine whether the violation is actually a violation or not - this usually arises due to the limitations of the rule engine or the rule itself. Therefore, it's up to the user to determine whether there is something to be done or not. That's where the difference is.

`Optional` is for deprecations and things like that - so a totally different thing. Here, the rule engine is sure that the issue raised is not mandatory for the migration to the target technology to be done.

**Comment by shawn-hurley** [comment]
This is an interesting distinction, and in this case, I am struggling to determine when and how the engine would determine that it does not have enough information and then would use that it. Could you give me an example of this?

**Comment by jmle** [comment]
You can take a look into the windup-rulesets repo and look for `category-id="potential"`, but here's an example: https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/eap7/eap72/maven-javax-to-jakarta.rhamt.xml#L180

**Comment by jmle** [comment]
The example that @rromannissen gave is good though - the packages found might or might not be a problem, therefore it's a potential problem which can't be identified for sure.

**Comment by fabianvf** [comment]
So would it be accurate to describe the distinction as

 - Confident, mandatory
 - Confident, optional
 - Unconfident

With the unconfident category existing for when your rule is a fairly basic heuristic, and you really want to express that to the user so they don't put too much weight into it?

**Comment by rromannissen** [comment]
The category is a conscious decision from the rules author, and has nothing to do with the level of confidence of the engine. It's not a matter of a full or partial match, as they require a full match like the others, but of how the author wants a certain rule to be classified. As you see, it's a value that appears on the rule definition itself. For an example of a catch-all rule, take a look at this one:

https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml#L49

This one looks for any proprietary weblogic.* or bea.* package and highlights it as a potential issue. It's information that the rules author is unsure of (this could or could not be a problem), but that could be useful for the end user, as it would provide hints on where to look for if all the other issues were fixed but the application still failed when deployed.

Potential issues are a way to still provide value in cases that the rules author hasn't faced yet, but that have potential to be problematic. 

For me, the example that @jmle provided doesn't qualify as potential, and all these rules should produce issues in the optional category instead.

**Comment by shawn-hurley** [comment]
After much discussion internally, we have agreed to the following changes (Please keep me honest folks :) )

1. Information rules will become tag or fact rules. 
2. We will continue to keep mandatory, optional, and potential as no one has come up with a better name for the potential to more clearly communicate that the rule author is unconfident of the problem, but suspects there could be one. 

We will work on this as part of demo D and make sure that the docs on these categories for rule authors help them understand. 

Thansk for the great discussion!
